### ISSUE TITLE
Error when testing call process and after subscribe

### ISSUE THREAD

**Issue by ilajosmanov** [logux/logux#41]
So, I have the error when calling process and then subscribe on the channel
But if I switch (first a channel and second process) — have no error

DB: MongoDB

```
await client1.process(createAccessory(doc));
await client2.subscribe("@accesories")
```

```
RangeError: Maximum call stack size exceeded

      at clone (node_modules/@logux/core/test-pair/index.cjs:3:16)
      at clone (node_modules/@logux/core/test-pair/index.cjs:9:19)
      at clone (node_modules/@logux/core/test-pair/index.cjs:9:19)
      at node_modules/@logux/core/test-pair/index.cjs:5:25
          at Array.map (<anonymous>)
      at clone (node_modules/@logux/core/test-pair/index.cjs:5:16)
      at clone (node_modules/@logux/core/test-pair/index.cjs:9:19)
      at clone (node_modules/@logux/core/test-pair/index.cjs:9:19)
      at node_modules/@logux/core/test-pair/index.cjs:5:25
          at Array.map (<anonymous>)
      at clone (node_modules/@logux/core/test-pair/index.cjs:5:16)
      at clone (node_modules/@logux/core/test-pair/index.cjs:9:19)
      at clone (node_modules/@logux/core/test-pair/index.cjs:9:19)
      at node_modules/@logux/core/test-pair/index.cjs:5:25
          at Array.map (<anonymous>)
      at clone (node_modules/@logux/core/test-pair/index.cjs:5:16)
```

**Comment by ai** [comment]
From `TestServer` in `@logux/server`? OK, I moved the issue to the right repo (we keep all issues in the same place).

What server code do you have? I afraid that error happens not because of the issue `TestClient`, but because of the error in `@logux/server` code.

**Comment by ilajosmanov** [comment]
![code](https://user-images.githubusercontent.com/18512404/85183439-5c336f00-b294-11ea-9157-30421105a2b8.png)
my server code

**Comment by ai** [comment]
@ilajosmanov can you copy it as text. I need to copy-paste the code to reproduce the error.

**Comment by ilajosmanov** [comment]
```
const accessoriesModule = (s: Server) => {
  s.channel("@accessories", {
    access: () => true,
    load: async () => {
      const docs = await Accessory.find();

      return {
        type: "@accessories/all",
        payload: docs
      };
    }
  });

  s.type(createAccessory, {
    access: () => true,
    resend: () => ({
      channel: "@accessories"
    }),
    process: async (_, {payload}) => {
      await new Accessory({
        ...payload,
        _id: mongoose.Types.ObjectId(),
      }).save();
    }
  });
};
```

**Comment by ai** [comment]
@ilajosmanov 

1. What is inside `createAccessory`?
2. Where is `@accessories/all` type definition?

**Comment by ilajosmanov** [comment]
1.
```
const createAction = actionCreatorFactory();
const createAccessory = createAction<IAccessoryRequest>("@accessory/create");
```
2. What do you mean?

**Comment by ai** [comment]
This code created an `@accessory/all` action:

```js
      return {
        type: "@accessories/all",
        payload: docs
      }
```

You need a `server.type('@accessories/all', { … })` call.

**Comment by ilajosmanov** [comment]
But `@accessries/all` needs to read data, but I want to create an accessory. It's should be a separate action, right?

**Comment by ai** [comment]
Yeap, it could be separated issue.

I also need the full file of tests.

**Comment by ilajosmanov** [comment]
I created `server.type("@accessories/all")` and called that. It's doesn't work.

Error: ` LoguxError: Logux received wrong-format error (Wrong message format in ["sync",5,null,{"id":-1592606446002,"time":-1592606446002}])`
```
const db = async (url: string) => {
  try {
    const connection = await mongoose.connect(url, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    console.info("Connected to: ", url);
    return connection;
  } catch (ex) {
    console.error(ex);
  }
};

describe("accessories", () => {
  let destroyable: TestServer;
  let connection: typeof import("mongoose");

  beforeAll(async () => {
    connection = await db(process.env.DATABASE_URL_TEST);
    await connection.connection.db.dropDatabase();
  });

  afterAll(() => {
    connection.disconnect();
  });

  afterEach(async () => {
    if (destroyable) {
      destroyable.destroy();
    }
  });

  const createServer = () => {
    destroyable = new TestServer();
    accessoriesModule(destroyable);
    return destroyable;
  };

  it("accessory successfully created", async () => {
    const s = createServer();
    const client = await s.connect("1");
    const client2 = await s.connect("2");

    const payload = {
      price: 2,
      quantity: 20,
      title: "Lorem ipsum",
      uid: "1",
      unitId: "1"
    };

    await client2.subscribe("@accessories");

    await client.process(createAccessory(payload));
    await client2.process(readAccessories);
  });
});
```

**Comment by ilajosmanov** [comment]
Problem solved!
This is because mongoDB sending a lot of properties.
When I changed my code to:
```
  s.channel("@accessories", {
    access: () => true,
    load: async () => {
      const docs = await Accessory
        .find()
        .select("title price quantity totalAmount uid unitId -_id");

      return {
        type: "@accessories/all",
        payload: docs.map(i => ({
          title: i.title,
          price: i.price,
          quantity: i.quantity,
          totalAmount: i.totalAmount,
          uid: i.uid
        }))
      };
    },
  });
```
