### ISSUE TITLE
Sending an Action from Rest Backend to Logux Proxy requires Meta ID, otherwise: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by cosminv6u** [logux/logux#50]
The BackendServer should be able to call the LoguxProxy via REST with an action where it specifies in the Meta only the Channels to retrieve the action, and not require the ID. Like this:

```
sendToLoguxProxy([
  { command: 'action', action, meta: { channel: 'cars' } }
])
```

"@logux/server": "^0.9.3"

```
FATAL  Cannot read property 'split' of null at 2020-07-09 12:47:15
        at C:\..\logux-proxy\node_modules\@logux\server\base-server\index.js:83:19
```

also reasons is required.

**Comment by ai** [comment]
Very strange:

1. You have an error in Logux Server’s [`preadd` event listener](https://github.com/logux/server/blob/master/base-server/index.js#L83).
2. Logux Server [uses](https://github.com/logux/server/blob/master/bind-backend-proxy/index.js#L99) the simple `log.add()` to add action from the backend.
3. `log.add` [calls](https://github.com/logux/core/blob/master/log/index.js#L34-L56) `preadd` only after setting `meta.id`.

N you show the full error stack trace and Java code of how do you do `sendToLoguxProxy`.

**Comment by cosminv6u** [comment]
Java Backend calls via Rest the LoguxProxy with the following Json body:

If I call it like this
```
{
	"version": 4,
	"secret": "mySecret",
	"commands": [
		{
			"command": "action",
			"action": {
				"type": "myAction",
				"myField": "myValue"
			},
			"meta": {
				"channels": [ "myChannel" ]
			}
		}
	]
}
```
I get
```
 FATAL  Expected "reasons" to be an array of strings at 2020-07-10 10:23:39
        at Log.add (./node_modules\@logux\core\log\index.cjs:47:13)
        at Object.command (./node_modules\@logux\server\bind-backend-proxy\index.js:102:24)
        at ...\node_modules\@logux\server\bind-control-server\index.js:86:57
        at Array.map (<anonymous>)
        at IncomingMessage.<anonymous> (./node_modules\@logux\server\bind-control-server\index.js:86:43)
        at IncomingMessage.emit (events.js:323:22)
        at endReadableNT (_stream_readable.js:1204:12)
        at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

If I add reasons:
```
{
	"version": 4,
	"secret": "mySecret",
	"commands": [
		{
			"command": "action",
			"action": {
				"type": "myAction",
				"myField": "myValue"
			},
			"meta": {
				"channels": [ "myChannel" ]
				"reasons": [ "myReason" ]
			}
		}
	]
}
```
I get
```
 FATAL  Cannot read property 'split' of null at 2020-07-10 10:30:53
        at ...\node_modules\@logux\server\base-server\index.js:83:19
        at Object.emit (./node_modules\nanoevents\index.cjs:5:7)
        at Log.add (./node_modules\@logux\core\log\index.cjs:56:18)
        at Object.command (./node_modules\@logux\server\bind-backend-proxy\index.js:102:24)
        at ...\node_modules\@logux\server\bind-control-server\index.js:86:57
        at Array.map (<anonymous>)
        at IncomingMessage.<anonymous> (./node_modules\@logux\server\bind-control-server\index.js:86:43)
        at IncomingMessage.emit (events.js:323:22)
        at endReadableNT (_stream_readable.js:1204:12)
        at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
If I add ID to meta it works, and I get in Logux Proxy log:
```
 INFO   Action was added at 2020-07-10 10:33:08
        Action:
          type:       "myAction"
          myField:    "myValue"
        Meta:
          id:          1594366388449 server:846XRio7 0                     // 846XRio7 is hardcoded by me
          time:        null
          subprotocol: null
          reasons:     ["myReason"]
          server:      "server:v4E6ok4C"
          channels:    ["myChannel"]
          status:      "processed"
          backend:     "127.0.0.1"
          added:       1
```

**Comment by ai** [comment]
The problem was in sending `id: null` from the backend server.

I am closing it since Back-end Protocol is semi-private and we are expecting that users use it right. Adding some hack will increase maintainability cost and promote dangerous behavior.
