### ISSUE TITLE
WebDriver.IO test fail randomly for Counter app

### ISSUE THREAD

**Issue by cosminv6u** [logux/logux#70]
[logux-tests.zip](https://github.com/logux/logux/files/5507491/logux-tests.zip)

I uploaded an archive with:
- logux nodejs server
- logux vuex app
- webdriver.io tests

The app is a Counter starting at 0 with 4 buttons:
- Increment
- IncrementALot (500 increments)
- Decrement 
- Reset (to 0)

+ Car: which has 3 buttons:
- Get Car: returns 'Dacia' only to the caller
- Save Car: saves 'Tesla' and resends to all subscribers
- Clear Car: clears the data (for tests)

When I run the tests one by one, it works fine.
When I manually do the tests in the browswer with my hand, it works fine.
When I run all tests one after the other, at least 1/2 tests fail, always different behavior.
I tried different pause values, so that test don't mess up one or the other, but still no luck (even set 50seconds wait between tests).

In each archive there are readme files saying how to start them.

Start the NodeJS Server, Start the Vuex App, then Run the WebDriverIO Tests.

It feels like some actions are not coming from Logux, I don't neccessarily get any logux error, just bad behavior (that's why the tests fail).

Sometimes I get many errors like these:

` ERROR  WS was closed at 2020-11-09 03:47:37
        at ServerConnection.send (./node_modules\@logux\core\ws-connection\index.cjs:72:34)
        at Server.debugError (./node_modules\@logux\server\base-server\index.js:410:24)
        at C:\java_dev\s4m\java_logux_server2\logux-nodejs-server\node_modules\@logux\server\base-server\index.js:180:44
        at Object.emit (./node_modules\nanoevents\index.cjs:5:7)
        at C:\java_dev\s4m\java_logux_server2\logux-nodejs-server\node_modules\@logux\server\server-client\index.js:47:24
        at Object.emit (./node_modules\nanoevents\index.cjs:5:7)
        at FilteredNode.error (./node_modules\@logux\core\base-node\index.cjs:228:18)
        at C:\java_dev\s4m\java_logux_server2\logux-nodejs-server\node_modules\@logux\core\base-node\index.cjs:95:16
        at Object.emit (./node_modules\nanoevents\index.cjs:5:7)
        at ServerConnection.send (./node_modules\@logux\core\ws-connection\index.cjs:72:20)
        Connection ID: 137

 ERROR  WS was closed at 2020-11-09 03:47:37
        at ServerConnection.send (./node_modules\@logux\core\ws-connection\index.cjs:72:34)
        at Server.debugError (./node_modules\@logux\server\base-server\index.js:410:24)
        at C:\java_dev\s4m\java_logux_server2\logux-nodejs-server\node_modules\@logux\server\base-server\index.js:180:44
        at Object.emit (./node_modules\nanoevents\index.cjs:5:7)
        at C:\java_dev\s4m\java_logux_server2\logux-nodejs-server\node_modules\@logux\server\server-client\index.js:47:24
        at Object.emit (./node_modules\nanoevents\index.cjs:5:7)
        at FilteredNode.error (./node_modules\@logux\core\base-node\index.cjs:228:18)
        at C:\java_dev\s4m\java_logux_server2\logux-nodejs-server\node_modules\@logux\core\base-node\index.cjs:95:16
        at Object.emit (./node_modules\nanoevents\index.cjs:5:7)
        at ServerConnection.send (./node_modules\@logux\core\ws-connection\index.cjs:72:20)
        Connection ID: 137`

**Comment by cosminv6u** [comment]
It was an issue with how I wrote the webdriver.io tests.

The only issue (that might be a feature, for DDoS), is when I send 500 sync messages in one second I get WS was closed error, and it disconnects me.
